import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';

const mock = new MockAdapter(axios);

const userList = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    address: 'Gwenborough',
    phone: '1-770-736-8031 x56442',
    website: 'hildegard.org',
    company: 'Romaguera-Crona',
    plan: 'Team',
    role: 'Maintainer',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    address: 'Wisokyburgh',
    phone: '010-692-6593 x09125',
    website: 'anastasia.net',
    company: 'Deckow-Crist',
    plan: 'Team',
    role: 'Maintainer',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    address: 'McKenziehaven',
    phone: '1-463-123-4447',
    website: 'ramiro.info',
    company: 'Romaguera-Jacobson',
    plan: 'Team',
    role: 'Maintainer',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    address: 'South Elvis',
    phone: '493-170-9623 x156',
    website: 'kale.biz',
    company: 'Robel-Corkery',
    plan: 'Basic',
    role: 'Subscriber',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    address: 'Roscoeview',
    phone: '(254)954-1289',
    website: 'demarco.info',
    company: 'Keebler LLC',
    plan: 'Basic',
    role: 'Subscriber',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    address: 'South Christy',
    phone: '1-477-935-8478 x6430',
    website: 'ola.org',
    company: 'Considine-Lockman',
    plan: 'Basic',
    role: 'Subscriber',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    address: 'Howemouth',
    phone: '210.067.6132',
    website: 'elvis.io',
    company: 'Johns Group',
    plan: 'Team',
    role: 'Subscriber',
    status: 'Active',
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    address: 'Aliyaview',
    phone: '586.493.6943 x140',
    website: 'jacynthe.com',
    company: 'Abernathy Group',
    plan: 'Team',
    role: 'Editor',
    status: 'Pending',
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    address: 'Bartholomebury',
    phone: '(775)976-6794 x41206',
    website: 'conrad.com',
    company: 'Yost and Sons',
    plan: 'Company',
    role: 'Editor',
    status: 'Pending',
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    address: 'Lebsackbury',
    phone: '024-648-3804',
    website: 'ambrose.net',
    company: 'Hoeger LLC',
    plan: 'Company',
    role: 'Author',
    status: 'Pending',
  },
  {
    id: 11,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    address: 'Gwenborough',
    phone: '1-770-736-8031 x56442',
    website: 'hildegard.org',
    company: 'Romaguera-Crona',
    plan: 'Enterprise',
    role: 'Author',
    status: 'Pending',
  },
  {
    id: 12,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    address: 'Wisokyburgh',
    phone: '010-692-6593 x09125',
    website: 'anastasia.net',
    company: 'Deckow-Crist',
    plan: 'Enterprise',
    role: 'Admin',
    status: 'Pending',
  },
  {
    id: 13,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    address: 'McKenziehaven',
    phone: '1-463-123-4447',
    website: 'ramiro.info',
    company: 'Romaguera-Jacobson',
    plan: 'Enterprise',
    role: 'Admin',
    status: 'Pending',
  },
  {
    id: 14,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    address: 'South Elvis',
    phone: '493-170-9623 x156',
    website: 'kale.biz',
    company: 'Robel-Corkery',
    plan: 'Enterprise',
    role: 'Maintainer',
    status: 'Inactive',
  },
  {
    id: 15,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    address: 'Roscoeview',
    phone: '(254)954-1289',
    website: 'demarco.info',
    company: 'Keebler LLC',
    plan: 'Team',
    role: 'Maintainer',
    status: 'Inactive',
  },
  {
    id: 16,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    address: 'South Christy',
    phone: '1-477-935-8478 x6430',
    website: 'ola.org',
    company: 'Considine-Lockman',
    plan: 'Team',
    role: 'Maintainer',
    status: 'Inactive',
  },
  {
    id: 17,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    address: 'Howemouth',
    phone: '210.067.6132',
    website: 'elvis.io',
    company: 'Johns Group',
    plan: 'Company',
    role: 'Maintainer',
    status: 'Inactive',
  },
  {
    id: 18,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    address: 'Aliyaview',
    phone: '586.493.6943 x140',
    website: 'jacynthe.com',
    company: 'Abernathy Group',
    plan: 'Company',
    role: 'Maintainer',
    status: 'Inactive',
  },
  {
    id: 19,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    address: 'Bartholomebury',
    phone: '(775)976-6794 x41206',
    website: 'conrad.com',
    company: 'Yost and Sons',
    plan: 'Company',
    role: 'Subscriber',
    status: 'Inactive',
  },
  {
    id: 20,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    address: 'Lebsackbury',
    phone: '024-648-3804',
    website: 'ambrose.net',
    company: 'Hoeger LLC',
    plan: 'Enterprise',
    role: 'Subscriber',
    status: 'Inactive',
  },
];

mock.onGet('/users').reply((config) => {
  const {
    query = '',
    role = 'All',
    plan = 'All',
    status = 'All',
  } = config.params;

  // lower case of all params
  const queryLower = query.toLowerCase();
  const roleLower = role.toLowerCase();
  const planLower = plan.toLowerCase();
  const statusLower = status.toLowerCase();

  const filterData = userList.filter(
    (user) => (user.name.toLowerCase().includes(queryLower)
     && (role === 'All' ? true : user.role.toLowerCase() === (roleLower || role))
      && (plan === 'All' ? true : user.plan.toLowerCase() === (planLower || plan))
      && (status === 'All' ? true : user.status.toLowerCase() === (statusLower || status))),
  );

  return [200, filterData];
});
